# Menus
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  Todo: todo
  About: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: gallery/avatar.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: y8n
        author_title: FrontEnd
        location: BeiJing, China
        follow: https://github.com/y8n
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: gallery/favicon.ico # path to favicon
    social_links:
        github: http://github.com/y8n
        weibo: http://weibo.com/u/5183172655
        mail:
            icon: envelope
            url: mailto:yjy972080142@gmail.com
        简书:
            icon: leaf
            url: http://www.jianshu.com/users/cd5539a6eb0f
        # twitter: /
        # facebook: /
        # dribbble: /
        # rss: /

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    # - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: false # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: # hexo-theme-icarus # enter disqus shortname here
    duoshuo: yangjiyuan # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: false # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: 66f517b45d32e4bdc3cd42db90367ff5 # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
